2025-09-22 14:11:06 [INFO] Starting USMNT update pipeline at 2025-09-22 14:11:06.572447.
2025-09-22 14:11:06 [INFO] Fetching latest player data...
2025-09-22 14:11:07 [INFO] Fetched 23 players data.
2025-09-22 14:11:07 [INFO] Connecting to the database...
2025-09-22 14:11:07 [INFO] Saving 23 players to the database...
2025-09-22 14:11:07 [INFO] 23/23 players saved...
2025-09-22 14:11:07 [INFO] All players saved successfully.
2025-09-22 14:11:07 [INFO] Database connection closed.
2025-09-22 14:11:07 [INFO] Saved 23 players to the database.
2025-09-22 14:11:07 [INFO] Updating player match stats...
2025-09-22 14:20:38 [INFO] Player stats updated successfully.
2025-09-22 14:20:38 [INFO] USMNT update pipeline completed successfully.

2025-09-29 14:10:21 [INFO] Starting USMNT update pipeline at 2025-09-29 14:10:21.337282.
2025-09-29 14:10:21 [INFO] Fetching latest player data...
2025-09-29 14:10:22 [INFO] Fetched 23 players data.
2025-09-29 14:10:22 [INFO] Connecting to the database...
2025-09-29 14:10:22 [INFO] Saving 23 players to the database...
2025-09-29 14:10:22 [INFO] 23/23 players saved...
2025-09-29 14:10:22 [INFO] All players saved successfully.
2025-09-29 14:10:22 [INFO] Database connection closed.
2025-09-29 14:10:22 [INFO] Saved 23 players to the database.
2025-09-29 14:10:22 [INFO] Updating player match stats...
2025-09-29 14:18:47 [INFO] Player stats updated successfully.
2025-09-29 14:18:47 [INFO] USMNT update pipeline completed successfully.

2025-10-06 14:10:14 [INFO] Starting USMNT update pipeline at 2025-10-06 14:10:14.625915.
2025-10-06 14:10:14 [INFO] Fetching latest player data...
2025-10-06 14:10:14 [INFO] Fetched 26 players data.
2025-10-06 14:10:14 [INFO] Connecting to the database...
2025-10-06 14:10:14 [INFO] Saving 26 players to the database...
2025-10-06 14:10:14 [INFO] 26/26 players saved...
2025-10-06 14:10:14 [INFO] All players saved successfully.
2025-10-06 14:10:14 [INFO] Database connection closed.
2025-10-06 14:10:14 [INFO] Saved 26 players to the database.
2025-10-06 14:10:14 [INFO] Updating player match stats...
2025-10-06 14:15:30 [ERROR] Error occurred during update pipeline.
Traceback (most recent call last):
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/update_pipeline.py", line 32, in job
    update_player_stats()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 324, in update_player_stats
    stats = parse_season_data(player)
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 110, in parse_season_data
    player_season_details_url = generate_player_details_url(tm_player_id, tm_player_url_name, club_name)
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 98, in generate_player_details_url
    club_code = team_country[club_name]
                ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'New England Revolution'
2025-10-13 14:11:00 [INFO] Starting USMNT update pipeline at 2025-10-13 14:11:00.257303.
2025-10-13 14:11:00 [INFO] Fetching latest player data...
2025-10-13 14:11:01 [INFO] Fetched 26 players data.
2025-10-13 14:11:01 [INFO] Connecting to the database...
2025-10-13 14:11:01 [INFO] Saving 26 players to the database...
2025-10-13 14:11:01 [INFO] 26/26 players saved...
2025-10-13 14:11:01 [INFO] All players saved successfully.
2025-10-13 14:11:01 [INFO] Database connection closed.
2025-10-13 14:11:01 [INFO] Saved 26 players to the database.
2025-10-13 14:11:01 [INFO] Updating player match stats...
2025-10-13 14:13:31 [ERROR] Error occurred during update pipeline.
Traceback (most recent call last):
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/update_pipeline.py", line 32, in job
    update_player_stats()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 332, in update_player_stats
    all_stats = pd.concat([all_stats, stats])
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
        objs,
    ...<8 lines>...
        sort=sort,
    )
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/core/reshape/concat.py", line 448, in __init__
    ndims = self._get_ndims(objs)
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/core/reshape/concat.py", line 489, in _get_ndims
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid
2025-10-15 03:02:27 [INFO] Starting USMNT update pipeline at 2025-10-15 03:02:27.850116.
2025-10-15 03:02:27 [INFO] Fetching latest player data...
2025-10-15 03:02:28 [INFO] Fetched 26 players data.
2025-10-15 03:02:28 [INFO] Connecting to the database...
2025-10-15 03:02:28 [INFO] Saving 26 players to the database...
2025-10-15 03:02:28 [INFO] 26/26 players saved...
2025-10-15 03:02:28 [INFO] All players saved successfully.
2025-10-15 03:02:28 [INFO] Database connection closed.
2025-10-15 03:02:28 [INFO] Saved 26 players to the database.
2025-10-15 03:02:28 [ERROR] Error occurred during update pipeline.
Traceback (most recent call last):
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/update_pipeline.py", line 29, in job
    players.to_csv('/players.csv', index=False)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/core/generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        path_or_buf,
        ^^^^^^^^^^^^
    ...<14 lines>...
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ~~~~~~~~~~^
        self.filepath_or_buffer,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        storage_options=self.storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handles:
    ^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
PermissionError: [Errno 13] Permission denied: '/players.csv'
2025-10-15 03:07:54 [INFO] Starting USMNT update pipeline at 2025-10-15 03:07:54.977311.
2025-10-15 03:07:54 [INFO] Fetching latest player data...
2025-10-15 03:07:55 [INFO] Fetched 26 players data.
2025-10-15 03:07:55 [INFO] Connecting to the database...
2025-10-15 03:07:55 [INFO] Saving 26 players to the database...
2025-10-15 03:07:55 [INFO] 26/26 players saved...
2025-10-15 03:07:55 [INFO] All players saved successfully.
2025-10-15 03:07:55 [INFO] Database connection closed.
2025-10-15 03:07:55 [INFO] Saved 26 players to the database.
2025-10-15 03:07:55 [INFO] Updating player match stats...
2025-10-15 03:12:35 [ERROR] Error occurred during update pipeline.
Traceback (most recent call last):
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/update_pipeline.py", line 33, in job
    update_player_stats()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 324, in update_player_stats
    stats = parse_season_data(player)
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 110, in parse_season_data
    player_season_details_url = generate_player_details_url(tm_player_id, tm_player_url_name, club_name)
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 98, in generate_player_details_url
    club_code = team_country[club_name]
                ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'New England Revolution'
2025-10-15 03:20:59 [INFO] Starting USMNT update pipeline at 2025-10-15 03:20:59.634835.
2025-10-15 03:20:59 [INFO] Fetching latest player data...
2025-10-15 03:21:00 [INFO] Fetched 26 players data.
2025-10-15 03:21:00 [INFO] Connecting to the database...
2025-10-15 03:21:00 [INFO] Saving 26 players to the database...
2025-10-15 03:21:00 [INFO] 26/26 players saved...
2025-10-15 03:21:00 [INFO] All players saved successfully.
2025-10-15 03:21:00 [INFO] Database connection closed.
2025-10-15 03:21:00 [INFO] Saved 26 players to the database.
2025-10-15 03:21:00 [INFO] Updating player match stats...
2025-10-15 03:23:34 [ERROR] Error occurred during update pipeline.
Traceback (most recent call last):
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/update_pipeline.py", line 33, in job
    update_player_stats()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/work/USMNT_Employee_Pipeline/USMNT_Employee_Pipeline/stats.py", line 332, in update_player_stats
    all_stats = pd.concat([all_stats, stats])
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
        objs,
    ...<8 lines>...
        sort=sort,
    )
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/core/reshape/concat.py", line 448, in __init__
    ndims = self._get_ndims(objs)
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/pandas/core/reshape/concat.py", line 489, in _get_ndims
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid
